# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestTask8thMarch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Fabric'
	pod 'Crashlytics'

  # Pods for TestTask8thMarch

end
